from __future__ import absolute_import
import random

verbs = [
  "Vitalize",
  "Interface",
  "Select",
  "Discuss",
  "Install",
  "Correct",
  "Synthesize",
  "Build",
  "Quote",
  "Frame",
  "Upgrade",
  "Coach",
  "Deduce",
  "Dispatch",
  "Transfer",
  "Bought",
  "Transport",
  "Display",
  "Detail",
  "Acquire",
  "Minimize",
  "Add",
  "Invent",
  "Conciliate",
  "Segment",
  "Merge",
  "Sample",
  "Derive",
  "Head",
  "Catalogue",
  "Depreciated",
  "Verify",
  "Map",
  "Innovate",
  "Conceptualize",
  "Influence",
  "Modernize",
  "Summarize",
  "Train",
  "Mechanize",
  "Appoint",
  "Construct",
  "Supervise",
  "Visualize",
  "Direct",
  "Specialize",
  "Manage",
  "Start",
  "Govern",
  "Study",
  "View",
  "Enhance",
  "Qualify",
  "Compute",
  "Ascertain",
  "Diagnose",
  "Demonstrate",
  "Arbitrate",
  "Cultivate",
  "Simulate",
  "License",
  "Facilitate",
  "Employ",
  "Complete",
  "Dissect",
  "Differentiate",
  "Rehabilitate",
  "Enlist",
  "Individualize",
  "Perceive",
  "Enlarge",
  "Restore",
  "Interpret",
  "Photograph",
  "Enumerate",
  "Experiment",
  "Charge",
  "Lead",
  "Cause",
  "Sustain",
  "Act",
  "Purchase",
  "Avert",
  "Accumulate",
  "Repair",
  "Equip",
  "Narrate",
  "Exercise",
  "Align",
  "Identify",
  "Enable",
  "Remodel",
  "Distinguish",
  "Publish",
  "Depict",
  "Upheld",
  "Author",
  "Assess",
  "Inspire",
  "Refer"
]

def next_inapp_event(num_sites=10000):
  num_domains = len(popular_domains)
  return "http://{0}/page{1}".format(
    popular_domains[random.randint(0, num_domains-1)],
    random.randint(1, num_sites / num_domains)
  )

